service: serverless-dynamodb-streams

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"

functions:
  updateProfile:
    handler: handler.updateProfile
  logger:
    handler: handler.logger
    events:
      - stream: arn:aws:dynamodb:us-east-1:595366274647:table/users/stream/2017-02-07T14:23:19.606
